spring:
  datasource:
    url: jdbc:mysql://database-1.c7oam6aom4ub.eu-north-1.rds.amazonaws.com:3306/quantity_db
    username: admin
    password: Mysql0001

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google_client_id}
            client-secret: ${google_client_secret_key}

  jpa:
    hibernate:
      ddl-auto: update

security:
  jwt:
    secret: ${jwt-secret-key}
server:
  address: 0.0.0.0